version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_PASSWORD=root
    volumes:
      - ./dbdata:/var/lib/mysql
  demo:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - 8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/mydb?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .:/home/spring/demo
    stdin_open: true
    tty: true
  angular:
    depends_on:
      - demo
    build: ./app/angulardockerproject
    volumes:
      - ./app/angulardockerproject:/usr/src/app
    ports:
      - 4200:80
#    command:
#      - bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

